### PR TITLE
rework to split role responsabilities

### PR DESCRIPTION
**Pull request by duck-rh**
So the goal is to define a draf to split the role responsabilities (server config, vhost config, specific instance config).

The WSGI part has been changed to have a consistent work and a working example of the third case.

This is just a draft to see if we can agree on changes, and I'll work on polishing and documenting along the way.

The mailing-lists-server role has been adapted to show a working example: https://gitlab.com/osas/ansible-role-mailing-lists-server/merge_requests/1

### CODE REVIEW

**Comment by mscherer** [comment]
So all I see is just renaming of a few files. What are the benefits of doing so ?

**Comment by duck-rh** [comment]
Well, you miss the point…

As discussed before (previous PR attempts…) and in the PR description I'm talking about 3 levels of configuration/responsabilities. If you look at the ML role example you'll see:

- the original goal of providing Apache default installation when used as dependency using the usual entry point (tasks/main.yml)

- a new _vhost_ entrypoint to define a vhost, which is meant to be used with _include_role_; same parameters as before but you need to modify the call

- the default installation retains the original behavior of creating the canonical vhost by hooking into the previous entrypoint internally, but with the additional behavior of not overwriting it if it already exists. This avoid destroying and recreating the configuration, generating Ansible changes count for nothing and leading to errors when you need to flush handlers in the middle (I had a case like when you add TLS config and the overwrite restart httpd with partial remaining TLS config files it failed; not sure to remember the exact details though)

- a new entrypoint to define a WSGI instance, so you can define the vhost details in your playbook and still have some role add WSGI support without messing the previous settings; also contrary to #25 you can have as many instances as you like

I should probably have written this, but it was late and I thought with all the discussions and a working example it would be fine.

So yes the changes are voluntarily made as thin as possible to avoid introducing new problems in this complex role. And the behavior is made to retain the previous good features and require not too much changes in existing playbooks. I thought you would prefer it this way.

**Comment by mscherer** [comment]
But that's because I miss the point that a diff alone wasn't enough to explain what you wanted to achieve. I think it could have been easier to start by the doc, to at least have a idea on how to use it and validate the "UX".  Right now, the default would be to get a vhost, cause anything else would break all others stuff. So that just leave include_role to be used for wsgi, is that correct ?

It is also a bit hard to reason on a change that do rename files, but also change variables names, add features, etc, especially trying to follow the execution flow just using the diff.

I also do not understand the removal of tls settings in the example. Is it a leftover of the tests (cf your other bug), or there is a subtility that I am missing (I would suppose the first, but better ask) ?

**Comment by duck-rh** [comment]
I like the idea of starting from the doc but it makes it really hard to design something implementable (unless you're ok to spend quite some time to fix/improve the current tooling to match your need), and avoid invasive and unreviewable changes. So as said it is a draft, and it can be reimplemented in another PR, or multiple ones.

As for features, it's true I should have refrained for changing http_common_*, my bad. Except from this, I think there is none. I will make a separate PR.

It's true I renamed 'allow_app_signals' and some files because it was unclear. I had to break the WSGI feature/API anyway. I just did not add some code to warn about it yet (this is a draft). Maybe I can isolate at least part of it in a separate PR.

The removal of the TLS settings is a mistake. I can't test it easily in a VM yet so I commented it out and forgot about it, sorry.

So I'd like your opinion on the API changes, at least from the outside at first.

**Comment by duck-rh** [comment]
Things a bit less mixed-up in my head today, so I split all unrelated or preparatory changes in separate PRs.

depends on #40 now

**Comment by duck-rh** [comment]
So, I had to add the entrypoint 'server', which should have been there from the start. As the call to the main entrypoint install all defaults, we may sometimes need to setup server-level parameters. At the moment there is only wsgi_allow_app_signals but we may add more in the future if needed.

The rationale is to decouple vhost generation and server parameters, and avoid relying on fragile constructs like having the first defined vhost setting this up.

So the logic would be: use_* + related variables needs to be used on the 'server' entrypoint if you need to change server-level parameters, and it needs to be used at vhost level too to get the defaults if you don't change server-level parameters. But I think this is fragile too. I would suggest we request that use_* is always setup at vhost level (for all vhost using the feature) whether you define server-level settings or not, whether it has any effect or not (a feature might only change server and instance level settings like WSGI), to avoid mistakes.

Hope that's not too unclear :-/

**Comment by mscherer** [comment]
That's unclear, yes. 

Having 4 interdependent PR that need to be merged and reviewed in a specific order is not helping much. This is also a recipe for being annoyed later since each modification in the first PR requires to rebase and change. 

As for the API, once the server part is split from vhost, do we have a good reason to keep wsgi settings in that role and not outside ? (as i think this could be a way to avoid bloating the role too much). 

In fact, what about maybe creating a httpd-vhost external role ? (I do have some reasons not to, but maybe the pro could outweight the cons)

**Comment by duck-rh** [comment]
I think the amount of code is small and not worth a split. Also in term of API you would have to make extra calls in the playbook and implement default/server/vhost and maybe instance entrypoints in each split role, so I would recommend it if the code grows too much in size or complexity. The only feature I see worth it now is the TLS support, but with the hardcoded port number handling (in vhost.yml) it is not yet possible. Also TLS is needed in almost all configurations so I think it is better in the core.

Anyway, we can change our mind later. I would rather work on this PR first, validate the new system, send potential subsequent fixes in one single place, and split later if needed in another PR.

**Comment by duck-rh** [comment]
Comment on recently pushed changes:

- modified documentation and added the missing part about WSGI

- in order not to require `use_wsgi` on the vhost level for doing nothing vhost-wise, I moved the loading of the defaults into the wsgi entrypoint, where I think it belongs

- unfortunately the `document_root` setting still needed to be repeated in the wsgi entrypoint, but that's redundant; the WSGI script needs a home which does not necessarily needs to be equal to the `document_root` so I created `wsgi_home` instead; what would have been nice is to make it default to the `document_root` value but we would need to store the vhost config somewhere (in the variable tree for example)

- I updated the meta to bump the required Ansible version

**Comment by duck-rh** [comment]
I'm withdrawing this work which will probably never be merged. If anyone is interested, please see https://gitlab.com/osas/ansible-role-ah-httpd instead.

**Pull request closed without merging**
