### PR TITLE
Fix regexp and backref for mod_security

### PR DESCRIPTION
**Pull request by mscherer**
I suspect it was working by error in the past, since it now fail.

### CODE REVIEW

**Comment by duck-rh** [comment]
As per the YAML format, I suspect changing the quoting is unrelated to the fix, no?

**Comment by mscherer** [comment]
Yup, that's the same but simpler. I can remove it, I just spent too much time fiddling around until I figured the missing backref: yes. Mod_security is slightly challenging to understand :)

**Comment by duck-rh** [comment]
it's fine.

**Comment by mscherer** [comment]
I suspect I also maybe need to move mod_security from system wide to vhost, but I am not yet familliar enough with it, and that's a rather complex beast to tame :/

**Pull request merged**
