### PR TITLE
Clarify variable  allow app signals

### PR DESCRIPTION
**Pull request by duck-rh**
depends on #39

### CODE REVIEW

**Comment by mscherer** [comment]
So I cherry picked this change and pushed, as it was easier to review and less headache to understand it. hence closing the PR without merging the 3 commits.

**Comment by duck-rh** [comment]
I can't find it in master,

**Comment by mscherer** [comment]
Mhh, i guess that I did push on my side since I do have some magic to push on my side and pull from the main repo. I also guess that's why I do dislike having PR with unrelated patches, it make the whole stuff more complicated by opening us to human errors :/

**Comment by duck-rh** [comment]
Well, I got your point last time on IRC; not sure how to improve without making working with many pending patches painful, but I'll try. In the meanwhile I'm back from vacation and this patch still is not in master, so I really don't know what I'm supposed to do.

**Comment by duck-rh** [comment]
reopening to merge only this specific commit

**Pull request merged**
